export const homeObjOne = {
    id: "think",
    TopLineCol: false,
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: "들어줄수 있는 사람이 되면 어떨까요?",
    headline: "저는 이렇게 생각해요",
    description: "듣고 생각하고 비즈니스 전반을 이해해야 좋은 개발자가 아닐까요?",
    darkText: false,
    buttonLabel: "도대체 무슨 이야기 하시는거죠?",
    imgStart: false,
    img: require("../../Logo/undraw_team_spirit_hrr4.svg"),
    alt: "Car",
    dark: true,
    primary: true,
};

export const homeObjTwo = {
    id: "thinkMore",
    TopLineCol: true,
    lightBg: true,
    lightText: false,
    lightTextDesc: true,
    topLine: "잠깐만요.",
    headline: "",
    description:
        "제가 드리고 싶은 말은 단순히 개발뿐만 아니라 비즈니스를 이해하고 자기가 쓰는 코드에 혼을 불어 넣는 사람이 여야 되지 않나 싶어요",
    darkText: true,
    buttonLabel: "그래서요?",
    imgStart: true,
    img: require("../../Logo/undraw_co-workers_ujs6.svg"),
    alt: "Car",
    dark: true,
    primary: true,
};

export const homeObjThree = {
    id: "aboutMe",
    TopLineCol: false,
    lightBg: false,
    lightText: true,
    lightTextDesc: false,
    topLine: "안녕하세요.",
    headline: "제 소개를 하겠습니다. 저는 백엔드 개발자 유병국이라고 합니다",
    description:
        "아직 할줄 아는 것보다 배워야 될게 많지만 앞서 말씀드린 이상을 가지고 열심히 노력하는 사람이 되겠습니다. 제 포트폴리오 한번 보시겠어요?",
    darkText: false,
    buttonLabel: "네",
    imgStart: false,
    img: require("../../Logo/F48749FB-356C-4360-82C9-0C550F5A7CA3_1_105_c.jpeg"),
    alt: "Car",
    dark: false,
    primary: true,
};
