export const homeObjOne = {
  id: "Think",
  TopLineCol: false,
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "저는 이렇게 생각합니다.",
  headline: "들어줄수 있는 사람이 되면 어떨까요?",
  description:
    "저도 오그라드는 말 싫어하지만 살다보니까 제 말을 들어주는 사람이 좋더라구요.",
  darkText: false,
  buttonLabel: "도대체 무슨 이야기 하시는거죠?",
  imgStart: false,
  img: require("../../Logo/undraw_Work_time_re_hdyv.svg"),
  alt: "Car",
  dark: true,
  primary: true,
};

export const homeObjTwo = {
  id: "ThinkMore",
  TopLineCol: true,
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "잠깐만요.",
  headline: "제가 드리고 싶은 말은 다른 사람 말을 잘 듣고 잘 배우는 사람",
  description: "이 좋은 개발자가 아닐까 싶어요!!",
  darkText: true,
  buttonLabel: "그래서요?",
  imgStart: true,
  img: require("../../Logo/undraw_Smiley_face_re_9uid.svg"),
  alt: "Car",
  dark: false,
  primary: false,
};

export const homeObjThree = {
  id: "AboutMe",
  TopLineCol: false,
  lightBg: false,
  lightText: true,
  lightTextDesc: false,
  topLine: "안녕하세요!!",
  headline: "저는 유병국이라고 합니다",
  description:
    "저는 미래의 Full Stack 개발자, 잘 듣고 잘 배우고 싶은 사람입니다. 아직 할 줄 아는 건 많이 없지만 열심히 잘 듣겠습니다.",
  darkText: false,
  buttonLabel: "그래서요?",
  imgStart: false,
  img: require("../../Logo/undraw_Smiley_face_re_9uid.svg"),
  alt: "Car",
  dark: false,
  primary: false,
};
